feat: add support for msg type 9
squidpickles/ais pull request #19
Opened 2024-08-20 16:19 UTC by salsabiljb

Added support for parsing AIS message type 9 (Standard SAR Aircraft Position Report), following this documentation [AIVDM/AIVDO protocol decoding](https://gpsd.gitlab.io/gpsd/AIVDM.html#_type_9_standard_sar_aircraft_position_report). I tested on a single message from the [gpsd test file](https://fossies.org/linux/gpsd/test/sample.aivdm).

with specialized parsers for altitude and speed over ground specific to AIS message type 9.

Also, compared the results with pyais using two messages (as shown in the attached image)
![Pasted image](https://github.com/user-attachments/assets/9ac733ec-831f-4e51-bee2-a2fddeaa9f78)

2024-08-21 03:01 UTC, squidpickles requested changes
Awesome! Code style matches the rest of the codebase, and these look correct against the test data I found. Only change is the one line in the tests.

2024-08-21 03:01 UTC, squidpickles commented on src/messages/standard_aircraft_position_report.rs
> +        assert_eq!(report.raim, false);
My clippy linter says this is better expressed as `assert!(!report.raim);`.

2024-08-21 08:58 UTC, salsabiljb commented on src/messages/standard_aircraft_position_report.rs
> +        assert_eq!(report.raim, false);
done!

2024-08-24 05:45 UTC, squidpickles approved these changes
Thanks for the contribution! Also, I appreciate your patience. I don't have a lot of time to devote to this codebase at the moment.

2024-08-24 05:52 UTC, merged